services:
  app:
    container_name: app
    image: marcelofabianov/php8.3-fpm-neo4j:latest
    build:
      context: ./_local/docker/app
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/var/www
      - ./.zshrc:/home/dev/.zshrc
      - ./.zsh_history:/home/dev/.zsh_history
    ports:
      - "8000:8000"
      - "9003:9003"
    networks:
      - app_network
    depends_on:
      - neo4j
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003"
      PHP_IDE_CONFIG: "serverName=app"

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    restart: always
    ports:
      - "7474:7474"  # Porta para acessar o navegador Neo4j
      - "7687:7687"  # Porta para comunicação Bolt
    environment:
      NEO4J_AUTH: neo4j/teste  # Definindo a autenticação (usuário e senha)
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"  # Aceitação do acordo de licença
    volumes:
      - neo4j_db:/data  # Volume para persistência dos dados do Neo4j

volumes:
  neo4j_db:
    driver: local

networks:
  app_network:
    driver: bridge
