services:
  app:
    container_name: app
    image: marcelofabianov/php8.3-fpm:latest
    build:
      context: ./_local/docker/app
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/var/www
      - ./.zshrc:/home/dev/.zshrc
      - ./.zsh_history:/home/dev/.zsh_history
    ports:
      - "8000:8000"
      - "9003:9003"
    networks:
      - app_network
    depends_on:
      - neo4j
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003"
      PHP_IDE_CONFIG: "serverName=app"

  neo4j:
    image: 'neo4j:5.19.0-community-bullseye'
    container_name: neo4j
    restart: always
    ports:
      - "11687:7687"
      - "11474:7474"
    environment:
      NEO4J_AUTH: neo4j/yPpiiQRxMTQ8qG
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_dbms_security_auth__minimum__password__length: 8
    volumes:
      - neo4j_db:/data

volumes:
  neo4j_db:
    driver: local

networks:
  app_network:
    driver: bridge
